name: JavaDoc

on:
  push

jobs:
  javadoc:
    uses: marchof/io.javaalmanac.javadocbuilder/.github/workflows/javadoc.yml@main
    with:
      version:      '10.0.2'
      repository:   'openjdk/jdk10u'
      tag:          'jdk-10.0.2+13'
      bootdownload: 'https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/download/jdk-10.0.2%2B13.1/OpenJDK10U-jdk_x64_linux_hotspot_10.0.2_13.tar.gz'
      apitarget:   'build/javadoc/images/docs/api'
      configure:    '--disable-warnings-as-errors --with-version-pre='
      licenses:     'LICENSE ASSEMBLY_EXCEPTION ADDITIONAL_LICENSE_INFO'
    secrets: inherit
