name: JavaDoc

on:
  push

jobs:
  javadoc:
    uses: marchof/io.javaalmanac.javadocbuilder/.github/workflows/javadoc.yml@main
    with:
      version:      '15.0.8'
      repository:   'openjdk/jdk15u'
      tag:          'jdk-15.0.8-ga'
      bootdownload: 'https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz'
      apitarget:    'build/javadoc/images/docs/api'
      configure:    '--with-version-pre='
      licenses:     'LICENSE ASSEMBLY_EXCEPTION ADDITIONAL_LICENSE_INFO'
    secrets: inherit
