name: JavaDoc

on:
  push

jobs:
  javadoc:
    uses: marchof/io.javaalmanac.javadocbuilder/.github/workflows/javadoc.yml@main
    with:
      version:     '11.0.18'
      repository:  'openjdk/jdk11u'
      tag:         'jdk-11.0.18-ga'
      bootdistro:  'temurin'
      bootversion: '11'
      apitarget:   'build/javadoc/images/docs/api'
      configure:   '--with-version-pre='
      licenses:    'LICENSE ASSEMBLY_EXCEPTION ADDITIONAL_LICENSE_INFO'
    secrets: inherit
