name: JavaDoc

on:
  push

jobs:
  javadoc:
    uses: marchof/io.javaalmanac.javadocbuilder/.github/workflows/javadoc.yml@main
    with:
      version:      '13.0.12'
      repository:   'openjdk/jdk13u'
      tag:          'jdk-13.0.12-ga'
      bootdownload: 'https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_linux_hotspot_13.0.2_8.tar.gz'
      apitarget:    'build/javadoc/images/docs/api'
      configure:    '--with-version-pre='
      licenses:     'LICENSE ASSEMBLY_EXCEPTION ADDITIONAL_LICENSE_INFO'
    secrets: inherit
